# Generated by Django 4.2.30 on 2026-07-19 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('field_schema', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('svg_asset', models.FileField(upload_to='templates/svg/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='designer.templategroup')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('order_number', models.CharField(max_length=100)),
                ('field_values', models.JSONField(blank=True, default=dict)),
                ('background_colour', models.CharField(blank=True, max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('details_submitted', 'Details submitted'), ('logo_uploaded', 'Logo uploaded'), ('logo_deferred', 'Logo deferred'), ('reminded', 'Client reminded'), ('escalated', 'Admin escalated'), ('complete', 'Complete')], default='details_submitted', max_length=20)),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design_requests', to='designer.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
