# Generated by Django 4.2.30 on 2026-07-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='request_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='designer.designrequest')),
            ],
        ),
    ]
