# Generated by Django 4.2.30 on 2026-07-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_designrequestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='logo_deferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
