# Generated by Django 4.2.30 on 2026-07-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_designrequest_logo_deferred_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='escalated_at',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='reminder_sent_at',
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('details_submitted', 'Details submitted'), ('logo_uploaded', 'Logo uploaded'), ('logo_deferred', 'Logo deferred'), ('complete', 'Complete')], default='details_submitted', max_length=20),
        ),
    ]
