# Generated by Django 4.2.30 on 2026-07-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_remove_designrequest_escalated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='logo_deferred_at',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='logo_file',
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('details_submitted', 'Details submitted'), ('logo_uploaded', 'Logo uploaded'), ('complete', 'Complete')], default='details_submitted', max_length=20),
        ),
        migrations.DeleteModel(
            name='DesignRequestFile',
        ),
    ]
