# Generated by Django 4.2.30 on 2026-07-20 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_remove_designrequest_logo_deferred_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('dropbox_path', models.CharField(max_length=500)),
                ('dropbox_link', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='designer.designrequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
