# Generated by Django 4.2.30 on 2026-07-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_designrequest_token_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='internal_number',
            field=models.PositiveIntegerField(blank=True, help_text='Internal reference number — not shown to clients.', null=True, unique=True),
        ),
    ]
