# Generated by Django 4.2.30 on 2026-07-24 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0009_backfill_banner_mesh_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templategroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_groups', to='designer.product'),
        ),
    ]
