# Generated by Django 4.2.30 on 2026-08-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0010_alter_templategroup_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Shown on the product-picker card grid.', upload_to='products/'),
        ),
    ]
